# Generated by Django 5.2.13 on 2026-04-26 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cambridge_practice', '0002_practiceattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_number', models.PositiveSmallIntegerField()),
                ('test_number', models.PositiveSmallIntegerField()),
                ('section', models.CharField(choices=[('listening', 'Listening'), ('reading', 'Reading')], max_length=20)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('scoring_rules', models.JSONField(blank=True, default=dict)),
                ('is_verified', models.BooleanField(default=False)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('book_number', 'test_number', 'section'),
                'constraints': [models.UniqueConstraint(fields=('book_number', 'test_number', 'section'), name='unique_answer_key_for_test_section')],
            },
        ),
        migrations.CreateModel(
            name='PracticeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('total_questions', models.PositiveSmallIntegerField(default=40)),
                ('submitted_answers', models.JSONField(blank=True, default=dict)),
                ('correct_answers', models.JSONField(blank=True, default=dict)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answer_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='cambridge_practice.answerkey')),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='cambridge_practice.practiceattempt')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
    ]
